# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:

  variables:
    APP: envars
  shell: /bin/bash

phases:

  install:
    on-failure: ABORT
    commands:
    - pip install pre-commit pytest

  build:
    on-failure: ABORT
    commands:
    - pre-commit run --all-files --show-diff-on-failure
    - pytest
